#!/usr/bin/env python3
"""
train.py — Fine-tune FLAN-T5-Small on Instagram comment→reply pairs.

Designed for CPU-only training on machines with 8–16 GB RAM.
Expects data generated by generate_dataset.py in data/train.json and data/val.json.

Usage:
    python train.py
    python train.py --epochs 5 --batch-size 2
"""

import argparse
import json
import os
import sys
import time

from datasets import Dataset
from transformers import (
    AutoModelForSeq2SeqLM,
    AutoTokenizer,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
)


# ── Constants ────────────────────────────────────────────────────────────────

MODEL_NAME = "google/flan-t5-small"
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "model", "insta-reply-flan-t5")
DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
TRAIN_FILE = os.path.join(DATA_DIR, "train.json")
VAL_FILE = os.path.join(DATA_DIR, "val.json")

MAX_INPUT_LENGTH = 128   # Max tokens for the comment input
MAX_TARGET_LENGTH = 128  # Max tokens for the reply output


# ── Data Loading ─────────────────────────────────────────────────────────────

def load_dataset_from_json(filepath: str) -> Dataset:
    """Load a JSON file of {"input": ..., "output": ...} pairs into a HF Dataset."""
    if not os.path.exists(filepath):
        print(f"❌ Error: Data file not found: {filepath}")
        print("   Run 'python generate_dataset.py' first to create the training data.")
        sys.exit(1)

    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    print(f"   Loaded {len(data)} examples from {os.path.basename(filepath)}")
    return Dataset.from_dict({
        "input": [item["input"] for item in data],
        "output": [item["output"] for item in data],
    })


# ── Tokenization ─────────────────────────────────────────────────────────────

def preprocess_function(examples, tokenizer):
    """Tokenize inputs and targets for Seq2Seq training."""
    model_inputs = tokenizer(
        examples["input"],
        max_length=MAX_INPUT_LENGTH,
        truncation=True,
    )

    labels = tokenizer(
        text_target=examples["output"],
        max_length=MAX_TARGET_LENGTH,
        truncation=True,
    )

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    import torch
    # Limit CPU threads to avoid context switching throttling on shared sandbox CPU
    torch.set_num_threads(2)

    parser = argparse.ArgumentParser(description="Fine-tune FLAN-T5-Small for Instagram comment replies")
    parser.add_argument("--epochs", type=int, default=5, help="Number of training epochs (default: 5)")
    parser.add_argument("--batch-size", type=int, default=4, help="Training batch size (default: 4)")
    parser.add_argument("--learning-rate", type=float, default=3e-4, help="Learning rate (default: 3e-4)")
    parser.add_argument("--grad-accum", type=int, default=4, help="Gradient accumulation steps (default: 4)")
    args = parser.parse_args()

    print()
    print("━" * 60)
    print("  🤖 InstaReply Bot — Model Training")
    print("━" * 60)
    print()

    # ── Step 1: Load data ────────────────────────────────────────────────
    print("📂 Loading datasets...")
    train_dataset = load_dataset_from_json(TRAIN_FILE)
    val_dataset = load_dataset_from_json(VAL_FILE)
    print()

    # ── Step 2: Load tokenizer & model ───────────────────────────────────
    print(f"📦 Loading model: {MODEL_NAME}")
    print("   (This may download ~300 MB on first run)")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

    param_count = sum(p.numel() for p in model.parameters())
    trainable_count = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"   Total parameters:     {param_count:,}")
    print(f"   Trainable parameters: {trainable_count:,}")
    print()

    # ── Step 3: Tokenize datasets ────────────────────────────────────────
    print("🔤 Tokenizing datasets...")
    tokenized_train = train_dataset.map(
        lambda examples: preprocess_function(examples, tokenizer),
        batched=True,
        remove_columns=train_dataset.column_names,
        desc="Tokenizing train",
    )
    tokenized_val = val_dataset.map(
        lambda examples: preprocess_function(examples, tokenizer),
        batched=True,
        remove_columns=val_dataset.column_names,
        desc="Tokenizing val",
    )
    print()

    # ── Step 4: Configure training ───────────────────────────────────────
    print("⚙️  Training configuration:")
    print(f"   Epochs:               {args.epochs}")
    print(f"   Batch size:           {args.batch_size}")
    print(f"   Gradient accumulation: {args.grad_accum}")
    print(f"   Effective batch size:  {args.batch_size * args.grad_accum}")
    print(f"   Learning rate:        {args.learning_rate}")
    print(f"   Device:               CPU")
    print(f"   Output directory:     {OUTPUT_DIR}")
    print()

    training_args = Seq2SeqTrainingArguments(
        output_dir=OUTPUT_DIR,
        num_train_epochs=args.epochs,
        per_device_train_batch_size=args.batch_size,
        per_device_eval_batch_size=args.batch_size,
        gradient_accumulation_steps=args.grad_accum,
        learning_rate=args.learning_rate,
        weight_decay=0.01,
        warmup_ratio=0.1,
        logging_steps=10,
        eval_strategy="epoch",
        save_strategy="epoch",
        save_total_limit=2,
        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        greater_is_better=False,
        predict_with_generate=False,
        fp16=False,  # CPU — no mixed precision
        report_to="none",
        use_cpu=True,
        dataloader_num_workers=0,
    )

    data_collator = DataCollatorForSeq2Seq(
        tokenizer=tokenizer,
        model=model,
        padding=True,
    )

    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_train,
        eval_dataset=tokenized_val,
        tokenizer=tokenizer,
        data_collator=data_collator,
    )

    # ── Step 5: Train! ───────────────────────────────────────────────────
    print("🚀 Starting training...")
    print("   (This may take 30–60 minutes on CPU)")
    print()

    start_time = time.time()
    trainer.train()
    elapsed = time.time() - start_time

    minutes = int(elapsed // 60)
    seconds = int(elapsed % 60)
    print()
    print(f"⏱️  Training completed in {minutes}m {seconds}s")
    print()

    # ── Step 6: Save the best model ──────────────────────────────────────
    final_dir = OUTPUT_DIR
    print(f"💾 Saving final model to: {final_dir}")
    trainer.save_model(final_dir)
    tokenizer.save_pretrained(final_dir)

    # Calculate saved model size
    total_size = 0
    for dirpath, dirnames, filenames in os.walk(final_dir):
        for f in filenames:
            fp = os.path.join(dirpath, f)
            total_size += os.path.getsize(fp)

    size_mb = total_size / (1024 * 1024)
    print(f"   Model size on disk: {size_mb:.1f} MB")
    print()
    print("━" * 60)
    print("  ✅ Training complete! Run 'python reply.py' to use the bot.")
    print("━" * 60)
    print()


if __name__ == "__main__":
    main()
